---
# tasks file for java12

- name: install wget
  yum :
   name: wget
   state: present

- name: download jdk12
  shell: wget https://mirrors.huaweicloud.com/java/jdk/12.0.1+12/jdk-12.0.1_linux-x64_bin.rpm

- name: install jdk 12
  shell: rpm -Uh jdk-12.0.1_linux-x64_bin.rpm